version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql5.7
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: 123
       MYSQL_USER: root
       MYSQL_PASSWORD: 123
    
networks:
  default:
    external:
      name: loteplus